%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.0036396310736977965     # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 0.0002596964676651332   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.0008113155966466435 # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 2.4392607370295274e-06    # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: /mavros/imu/data
