%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.00331461578      # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 3.2050104214554934e-04   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.00012676715  # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 4.68531868635797e-06    # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: /imu/data
