%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.0070082399     # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 5.363279036529108e-4   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.0050932053 # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 2.406437168579788e-03    # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: /livox/imu
