%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.00446194576   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 4.916409164708649e-04    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.00032884011    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 9.414492341581255e-06     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: "/mavros/imu/data_raw"
