%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.005457397459599346     # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 6.113996506614726e-04   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 2.5168513991925153e-04 # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 4.878091752029107e-06    # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: /imu/data
