%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.003106841831492606   # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 0.00042920031805729667   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 0.0006131762341621405   # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 8.894361051134189e-06    # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: /oak_d_pro/imu/data
